export const ACTION_FIRST = 'ACTION_FIRST';
export const ACTION_SECOND = 'ACTION_SECOND';

export const MUTATIONS_START_ACTION_FIRST = 'MUTATIONS_START_ACTION_FIRST';
export const MUTATIONS_END_ACTION_FIRST_SUCCESS = 'MUTATIONS_END_ACTION_FIRST_SUCCESS';
export const MUTATIONS_END_ACTION_FIRST_FAILURE = 'MUTATIONS_END_ACTION_FIRST_FAILURE';

export const MUTATIONS_START_ACTION_SECOND = 'MUTATIONS_START_ACTION_SECOND';
export const MUTATIONS_END_ACTION_SECOND_SUCCESS = 'MUTATIONS_END_ACTION_SECOND_SUCCESS';
export const MUTATIONS_END_ACTION_SECOND_FAILURE = 'MUTATIONS_END_ACTION_SECOND_FAILURE';
